<?php

declare(strict_types=1);

/**
 * NOBS — Nuclear Order Bit Syndicate
 *
 * Copyright (C) 2026 RawSmoke <https://nobs.rawsmoke.net>
 *
 * Obra original de NOBS, parte de un derivado de UNIT3D Community Edition
 * (HDInnovations) del que hereda la licencia.
 *
 * @project    NOBS — https://nobs.rawsmoke.net
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html  GNU AGPL v3.0
 */

/**
 * Catálogo del Arcade ScummVM.
 *
 * Fuente única de verdad para los juegos disponibles. Tanto el controlador
 * (GamingController) como el INI generado para ScummVM se construyen a partir
 * de aquí. Para añadir un juego: copiar los datos a public/games/<id>/, la
 * portada a public/img/games/<id>.{png,jpg}, y registrar la entrada abajo.
 *
 * El orden de las entradas determina el orden de visualización en el índice.
 * Política actual: agrupar por saga (Monkey Island → Indiana Jones → Maniac
 * Mansion → standalones cronológicos).
 *
 * Campos por entrada:
 *   titulo, descripcion, año, desarrollador, idioma, version  → metadatos UI
 *   engine_id      → motor ScummVM (debe corresponder a un libxxx.so en
 *                    public/engine/data/plugins/). Whitelist: ^[a-z][a-z0-9]*$
 *   scummvm_id     → "target" interno de ScummVM (sección INI). Único en el
 *                    catálogo.  Whitelist: ^[a-z][a-z0-9-]*$
 *   cover          → ruta al PNG/JPG de portada
 *   files          → lista relativa a public/games/<id>/ (admite subdirs como
 *                    'DATA/foo.SAN' para juegos con layout anidado tipo FT)
 *   ini            → opcional. Sobreescribe valores en scummvm.ini. Soporta:
 *                      language     (string)  — código de idioma p.ej. 'es'
 *                      subtitles    (bool)
 *                      aspect_ratio (bool)    — false para desactivar
 *   gameid         → opcional. ID canónico de ScummVM (lo que va en gameid=).
 *                    Por defecto se asume igual a scummvm_id. Sólo necesario
 *                    cuando varias entradas comparten el mismo juego canónico
 *                    (p.ej. mi1-vga e yonkey son ambos gameid=monkey pero
 *                    deben tener scummvm_id distintos como sección INI).
 */
return [
    'catalog' => [
        // ─── Monkey Island series ─────────────────────────────────────────
        'mi1-vga' => [
            'titulo'        => 'The Secret of Monkey Island',
            'descripcion'   => 'La legendaria aventura gráfica de LucasArts que comenzó todo, en su edición CD Talkie con doblaje y banda sonora orquestada. Guía a Guybrush Threepwood en su camino para convertirse en el pirata definitivo.',
            'año'           => 1990,
            'desarrollador' => 'LucasArts',
            'idioma'        => 'Español',
            'version'       => 'CD Talkie',
            'engine_id'     => 'scumm',
            'scummvm_id'    => 'monkey',
            'cover'         => '/img/games/mi1-vga.jpg',
            'files'         => [
                'monkey.000', 'monkey.001', 'monkey.sog',
                'track1.ogg', 'track2.ogg', 'track3.ogg', 'track4.ogg', 'track5.ogg',
                'track6.ogg', 'track7.ogg', 'track8.ogg', 'track8_no_sfx.ogg', 'track9.ogg',
                'track10.ogg', 'track11.ogg', 'track12.ogg', 'track13.ogg', 'track14.ogg',
                'track15.ogg', 'track16.ogg', 'track17.ogg', 'track18.ogg', 'track19.ogg',
                'track20.ogg', 'track21.ogg', 'track22.ogg', 'track23.ogg', 'track24.ogg',
                'track25.ogg', 'track26.ogg', 'track27.ogg', 'track28.ogg', 'track29.ogg',
            ],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

        'mi2-talkie' => [
            'titulo'        => "Monkey Island 2: LeChuck's Revenge",
            'descripcion'   => 'Guybrush busca el legendario tesoro de Big Whoop mientras LeChuck regresa más peligroso que nunca. Versión española con subtítulos completos.',
            'año'           => 1992,
            'desarrollador' => 'LucasArts',
            'idioma'        => 'Español',
            'version'       => 'CD Talkie',
            'engine_id'     => 'scumm',
            'scummvm_id'    => 'monkey2',
            'cover'         => '/img/games/mi2-talkie.jpg',
            'files'         => ['MONKEY2.000', 'MONKEY2.001', 'monkey2.sog'],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

        'comi' => [
            'titulo'        => 'The Curse of Monkey Island',
            'descripcion'   => 'La tercera aventura de Guybrush Threepwood, ahora dibujada a mano al estilo Disney. LeChuck transforma a Elaine en estatua de oro y sólo una maldición pirata desatada por un anillo puede salvarla. SCUMM v8 — la cima técnica del motor.',
            'año'           => 1997,
            'desarrollador' => 'LucasArts',
            'idioma'        => 'Español',
            'version'       => 'CD Talkie',
            'engine_id'     => 'scumm',
            'scummvm_id'    => 'comi',
            'cover'         => '/img/games/comi.jpg',
            'files'         => [
                'comi.la0', 'comi.la1', 'comi.la2',
                'resource/BBSAN.SAN', 'resource/CURSERNG.SAN', 'resource/FG010GP.SAN',
                'resource/FINALE.SAN', 'resource/FONT0.NUT', 'resource/FONT1.NUT',
                'resource/FONT2.NUT', 'resource/FONT3.NUT', 'resource/FONT4.NUT',
                'resource/KIS030.SAN', 'resource/LANGUAGE.TAB', 'resource/LAVARIDE.SAN',
                'resource/LIFTCRSE.SAN', 'resource/MORESLAW.SAN', 'resource/MUSDISK1.BUN',
                'resource/MUSDISK2.BUN', 'resource/NEWBOOTS.SAN', 'resource/OPENING.SAN',
                'resource/SB010.SAN', 'resource/SB020.SAN', 'resource/SINKSHP.SAN',
                'resource/VOXDISK1.BUN', 'resource/VOXDISK2.BUN', 'resource/WRECKSAN.SAN',
                'resource/ZAP010.SAN',
            ],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

        'yonkey' => [
            'titulo'        => 'Yonkey Island 1.0',
            'descripcion'   => 'Traducción charnega y desternillante de Monkey Island por Charnego Translations. Mismo juego, mismo Guybrush, pero con un toque andaluz que hay que vivir para creer.',
            'año'           => 2023,
            'desarrollador' => 'LucasArts / Charnego Translations',
            'idioma'        => 'Charnego (ES)',
            'version'       => 'CD Talkie · Fan-trans',
            'engine_id'     => 'scumm',
            'scummvm_id'    => 'yonkey',
            'gameid'        => 'monkey',
            'cover'         => '/img/games/yonkey.jpg',
            'files'         => [
                'monkey.000', 'monkey.001',
                'track1.ogg', 'track2.ogg', 'track3.ogg', 'track4.ogg', 'track5.ogg',
                'track6.ogg', 'track7.ogg', 'track8.ogg', 'track9.ogg', 'track10.ogg',
                'track11.ogg', 'track12.ogg', 'track13.ogg', 'track14.ogg', 'track15.ogg',
                'track16.ogg', 'track17.ogg', 'track18.ogg', 'track19.ogg', 'track20.ogg',
                'track21.ogg', 'track22.ogg', 'track23.ogg', 'track24.ogg',
            ],
            'ini'           => ['subtitles' => true],
        ],

        // ─── Indiana Jones series ─────────────────────────────────────────
        'indy3' => [
            'titulo'        => 'Indiana Jones y la Última Cruzada',
            'descripcion'   => 'La aventura gráfica que precede a Atlántida: Indy y su padre rastrean el Santo Grial mientras los nazis pisan sus talones. Sistema IQ pionero y múltiples soluciones por puzzle, en español.',
            'año'           => 1989,
            'desarrollador' => 'LucasArts',
            'idioma'        => 'Español',
            'version'       => 'VGA Floppy',
            'engine_id'     => 'scumm',
            'scummvm_id'    => 'indy3',
            'cover'         => '/img/games/indy3.png',
            'files'         => [
                '00.lfl', '01.lfl', '02.lfl', '03.lfl', '04.lfl', '06.lfl', '07.lfl', '08.lfl', '09.lfl',
                '12.lfl', '13.lfl', '14.lfl', '15.lfl', '16.lfl', '17.lfl', '18.lfl', '19.lfl', '20.lfl',
                '21.lfl', '22.lfl', '23.lfl', '24.lfl', '25.lfl', '26.lfl', '27.lfl', '28.lfl', '29.lfl',
                '30.lfl', '31.lfl', '32.lfl', '33.lfl', '34.lfl', '35.lfl', '36.lfl', '37.lfl', '38.lfl',
                '39.lfl', '40.lfl', '41.lfl', '42.lfl', '43.lfl', '44.lfl', '45.lfl', '46.lfl', '47.lfl',
                '48.lfl', '49.lfl', '50.lfl', '51.lfl', '52.lfl', '53.lfl', '54.lfl', '55.lfl', '56.lfl',
                '57.lfl', '58.lfl', '59.lfl', '60.lfl', '61.lfl', '62.lfl', '63.lfl', '64.lfl', '66.lfl',
                '67.lfl', '68.lfl', '69.lfl', '70.lfl', '71.lfl', '72.lfl', '73.lfl', '74.lfl', '75.lfl',
                '76.lfl', '77.lfl', '78.lfl', '79.lfl', '80.lfl', '81.lfl', '82.lfl', '83.lfl', '84.lfl',
                '85.lfl', '86.lfl', '87.lfl', '90.lfl', '91.lfl', '93.lfl', '94.lfl', '98.lfl', '99.lfl',
            ],
            'ini'           => ['language' => 'es'],
        ],

        'indy-atlantis' => [
            'titulo'        => 'Indiana Jones y el Destino de la Atlántida',
            'descripcion'   => 'Indiana Jones busca la legendaria Atlántida antes de que los nazis la usen para fabricar un arma suprema. Múltiples caminos y decisiones en esta épica aventura, con voces y textos en español.',
            'año'           => 1992,
            'desarrollador' => 'LucasArts',
            'idioma'        => 'Español',
            'version'       => 'CD Talkie',
            'engine_id'     => 'scumm',
            'scummvm_id'    => 'atlantis',
            'cover'         => '/img/games/indy-atlantis.png',
            'files'         => ['atlantis.000', 'atlantis.001', 'monster.so3'],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

        // ─── Maniac Mansion series ────────────────────────────────────────
        'maniac-mansion' => [
            'titulo'        => 'Maniac Mansion',
            'descripcion'   => 'La primera gran aventura gráfica de LucasArts, ahora en español. Rescata a Sandy de las garras del Dr. Fred y su meteorito mutante en esta mansión llena de secretos.',
            'año'           => 1987,
            'desarrollador' => 'LucasArts',
            'idioma'        => 'Español',
            'version'       => 'Enhanced',
            'engine_id'     => 'scumm',
            'scummvm_id'    => 'maniac',
            'cover'         => '/img/games/maniac-mansion.png',
            'files'         => [
                '00.lfl', '01.lfl', '02.lfl', '03.lfl', '04.lfl', '05.lfl', '06.lfl', '07.lfl',
                '08.lfl', '09.lfl', '10.lfl', '11.lfl', '12.lfl', '13.lfl', '14.lfl', '15.lfl',
                '16.lfl', '17.lfl', '18.lfl', '19.lfl', '20.lfl', '21.lfl', '22.lfl', '23.lfl',
                '24.lfl', '25.lfl', '26.lfl', '27.lfl', '28.lfl', '29.lfl', '30.lfl', '31.lfl',
                '32.lfl', '33.lfl', '34.lfl', '35.lfl', '36.lfl', '37.lfl', '38.lfl', '39.lfl',
                '40.lfl', '41.lfl', '42.lfl', '43.lfl', '44.lfl', '45.lfl', '46.lfl', '47.lfl',
                '48.lfl', '49.lfl', '50.lfl', '51.lfl', '52.lfl', '53.lfl',
            ],
            'ini'           => ['language' => 'es'],
        ],

        'tentacle' => [
            'titulo'        => 'Maniac Mansion 2: El Día del Tentáculo',
            'descripcion'   => 'Bernard, Hoagie y Laverne viajan en el tiempo para impedir que el Tentáculo Púrpura conquiste el mundo. La secuela de Maniac Mansion, con humor desatado y puzzles enrevesados.',
            'año'           => 1993,
            'desarrollador' => 'LucasArts',
            'idioma'        => 'Español',
            'version'       => 'Floppy',
            'engine_id'     => 'scumm',
            'scummvm_id'    => 'tentacle',
            'cover'         => '/img/games/tentacle.jpg',
            'files'         => ['tentacle.000', 'tentacle.001', 'monster.sou'],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

        // ─── Other LucasArts classics (chronological) ────────────────────
        'zak-mckracken' => [
            'titulo'        => 'Zak McKracken and the Alien Mindbenders',
            'descripcion'   => 'Un periodista de tabloides descubre una conspiración alienígena para reducir la inteligencia humana, ahora con textos en español. Viaja por todo el mundo para salvar la humanidad.',
            'año'           => 1988,
            'desarrollador' => 'LucasArts',
            'idioma'        => 'Español',
            'version'       => 'FM Towns',
            'engine_id'     => 'scumm',
            'scummvm_id'    => 'zak',
            'cover'         => '/img/games/zak-mckracken.png',
            'files'         => [
                '00.lfl', '01.lfl', '02.lfl', '03.lfl', '04.lfl', '05.lfl', '06.lfl', '07.lfl',
                '08.lfl', '09.lfl', '10.lfl', '11.lfl', '12.lfl', '13.lfl', '14.lfl', '15.lfl',
                '16.lfl', '17.lfl', '18.lfl', '19.lfl', '20.lfl', '21.lfl', '22.lfl', '23.lfl',
                '24.lfl', '25.lfl', '26.lfl', '27.lfl', '28.lfl', '29.lfl', '30.lfl', '31.lfl',
                '32.lfl', '33.lfl', '34.lfl', '35.lfl', '36.lfl', '37.lfl', '38.lfl', '39.lfl',
                '40.lfl', '41.lfl', '42.lfl', '43.lfl', '44.lfl', '45.lfl', '46.lfl', '47.lfl',
                '48.lfl', '49.lfl', '50.lfl', '51.lfl', '52.lfl', '53.lfl', '54.lfl', '55.lfl',
                '56.lfl', '57.lfl', '58.lfl', '59.lfl', '98.lfl', '99.lfl',
                'track1.ogg', 'track2.ogg', 'track3.ogg', 'track4.ogg', 'track5.ogg',
                'track6.ogg', 'track7.ogg', 'track8.ogg', 'track9.ogg', 'track10.ogg',
                'track11.ogg', 'track12.ogg', 'track13.ogg', 'track14.ogg', 'track15.ogg',
                'track16.ogg', 'track17.ogg', 'track18.ogg', 'track19.ogg', 'track20.ogg', 'track21.ogg',
            ],
            // 'extra=FM-TOWNS' marca la variante; 'audio_override' obliga al engine
            // a usar las pistas track*.ogg presentes en /games/zak-mckracken/.
            'ini'           => ['language' => 'es', 'aspect_ratio' => false, 'extra' => 'FM-TOWNS', 'audio_override' => true, 'cdrom' => 1, 'guioptions' => 'GAMEOPTION_AUDIO_OVERRIDE'],
        ],

        'loom' => [
            'titulo'        => 'Loom',
            'descripcion'   => 'Una aventura de fantasía única donde la magia se ejerce tejiendo melodías, ahora con textos en español. Bobbin Threadbare debe salvar a su gremio de tejedores de una oscuridad creciente.',
            'año'           => 1990,
            'desarrollador' => 'LucasArts',
            'idioma'        => 'Español',
            'version'       => 'CD Talkie',
            'engine_id'     => 'scumm',
            // 'loomcd' es un target explícito en libscumm.so para la variante CD;
            // se complementa con audio_override por si la detección runtime aún
            // no asocia las pistas externas con el reemplazo de CD audio.
            'scummvm_id'    => 'loomcd',
            'gameid'        => 'loom',
            'cover'         => '/img/games/loom.png',
            'files'         => ['000.lfl', '901.lfl', '902.lfl', '903.lfl', '904.lfl', 'disk01.lec', 'track1.mp3'],
            'ini'           => ['language' => 'es', 'subtitles' => true, 'audio_override' => true, 'cdrom' => 1, 'guioptions' => 'GAMEOPTION_AUDIO_OVERRIDE'],
        ],

        'samnmax' => [
            'titulo'        => 'Sam & Max Hit the Road',
            'descripcion'   => 'El dúo detective más disparatado del mundo investiga la desaparición de un Bigfoot de feria. Una comedia absurda y brillante por la América profunda.',
            'año'           => 1993,
            'desarrollador' => 'LucasArts',
            'idioma'        => 'Inglés',
            'version'       => 'CD Talkie',
            'engine_id'     => 'scumm',
            'scummvm_id'    => 'samnmax',
            'cover'         => '/img/games/samnmax.png',
            'files'         => ['samnmax.000', 'samnmax.001', 'monster.sog'],
        ],

        'dig' => [
            'titulo'        => 'The Dig',
            'descripcion'   => 'Una historia de ciencia ficción co-creada por Steven Spielberg: un equipo de astronautas atrapado en un asteroide alienígena descubre los secretos de una civilización perdida. Aventura atmosférica de LucasArts, doblada al español.',
            'año'           => 1995,
            'desarrollador' => 'LucasArts',
            'idioma'        => 'Español',
            'version'       => 'CD Talkie',
            'engine_id'     => 'scumm',
            'scummvm_id'    => 'dig',
            'cover'         => '/img/games/dig.jpg',
            'files'         => [
                'dig.la0', 'dig.la1', 'digmusic.bun', 'digvoice.bun', 'language.bnd',
                'video/ALCOVE.SAN', 'video/ASTTUN.SAN', 'video/DARKCAVE.SAN', 'video/DIGTXT.TRS',
                'video/FONT0.NUT', 'video/FONT1.NUT', 'video/FONT2.NUT', 'video/FONT3.NUT',
                'video/M1.SAN', 'video/M2.SAN', 'video/NEXUSPAN.SAN', 'video/PIGOUT.SAN',
                'video/RTRAM1.SAN', 'video/RTRAM2.SAN', 'video/RTRAM3.SAN', 'video/RTRAM4.SAN',
                'video/RTRAM5.SAN', 'video/SKY.SAN', 'video/SQ1.SAN', 'video/SQ2.SAN',
                'video/SQ3.SAN', 'video/SQ4.SAN', 'video/SQ5.SAN', 'video/SQ6.SAN',
                'video/SQ6SC3.SAN', 'video/SQ7.SAN', 'video/SQ8A.SAN', 'video/SQ8A1.SAN',
                'video/SQ8B.SAN', 'video/SQ8C.SAN', 'video/SQ9.SAN', 'video/SQ10.SAN',
                'video/SQ11.SAN', 'video/SQ12A.SAN', 'video/SQ12B.SAN', 'video/SQ13.SAN',
                'video/SQ14B.SAN', 'video/SQ14SC04.SAN', 'video/SQ14SC07.SAN', 'video/SQ14SC11.SAN',
                'video/SQ14SC14.SAN', 'video/SQ14SC16.SAN', 'video/SQ14SC19.SAN', 'video/SQ14SC22.SAN',
                'video/SQ15A.SAN', 'video/SQ15B.SAN', 'video/SQ17.SAN', 'video/SQ18A.SAN',
                'video/SQ18B.SAN', 'video/SQ18SC15.SAN', 'video/SQ19A.SAN', 'video/SQ19B.SAN',
                'video/SQ19C.SAN', 'video/TOMBDWN1.SAN', 'video/TOMBDWN2.SAN',
                'video/TRAM1.SAN', 'video/TRAM2.SAN', 'video/TRAM3.SAN', 'video/TRAM4.SAN',
                'video/TRAM5.SAN',
            ],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

        'ft' => [
            'titulo'        => 'Full Throttle',
            'descripcion'   => 'Ben, líder de la banda motera Polecats, se ve atrapado en una trama de asesinato corporativo. Una aventura grasienta de moteros, carreteras y rock, doblada al español.',
            'año'           => 1995,
            'desarrollador' => 'LucasArts',
            'idioma'        => 'Español',
            'version'       => 'CD Talkie',
            'engine_id'     => 'scumm',
            'scummvm_id'    => 'ft',
            'cover'         => '/img/games/ft.jpg',
            'files'         => [
                'ft.la0', 'ft.la1', 'monster.sou',
                'DATA/BENCUT.NUT', 'DATA/BENFLIP.SAN', 'DATA/BENSGOGG.NUT', 'DATA/CHASOUT.SAN',
                'DATA/CHASTHRU.SAN', 'DATA/FISHFEAR.SAN', 'DATA/FISHGOG2.SAN', 'DATA/FISHGOGG.SAN',
                'DATA/GETNITRO.SAN', 'DATA/GOGLPALT.RIP', 'DATA/HITDUST1.SAN', 'DATA/HITDUST2.SAN',
                'DATA/HITDUST3.SAN', 'DATA/HITDUST4.SAN', 'DATA/ICONS.NUT', 'DATA/ICONS2.NUT',
                'DATA/LIFTBORD.SAN', 'DATA/LIFTCHAY.SAN', 'DATA/LIFTGOG.SAN', 'DATA/LIFTMACE.SAN',
                'DATA/LIFTSAW.SAN', 'DATA/LIMOCRSH.SAN', 'DATA/MINEDRIV.FLU', 'DATA/MINEDRIV.SAN',
                'DATA/MINEEXIT.SAN', 'DATA/MINEFITE.FLU', 'DATA/MINEFITE.SAN', 'DATA/MINEROAD.TRS',
                'DATA/ROADRASH.RIP', 'DATA/ROADRSH2.RIP', 'DATA/ROADRSH3.RIP', 'DATA/ROTTFITE.SAN',
                'DATA/ROTTFLIP.SAN', 'DATA/ROTTOPEN.SAN', 'DATA/SCUMMFNT.NUT', 'DATA/SPECFNT.NUT',
                'DATA/TECHFNT.NUT', 'DATA/TITLFNT.NUT', 'DATA/TOMINE.SAN', 'DATA/TORANCH.FLU',
                'DATA/TORANCH.SAN', 'DATA/TOVISTA1.FLU', 'DATA/TOVISTA1.SAN', 'DATA/TOVISTA2.FLU',
                'DATA/TOVISTA2.SAN', 'DATA/VISTTHRU.SAN', 'DATA/WR2_BEN.SAN', 'DATA/WR2_BENC.SAN',
                'DATA/WR2_BENR.SAN', 'DATA/WR2_BENV.SAN', 'DATA/WR2_CAVE.SAN', 'DATA/WR2_CVKO.SAN',
                'DATA/WR2_ROTT.SAN', 'DATA/WR2_VLTC.SAN', 'DATA/WR2_VLTP.SAN', 'DATA/WR2_VLTS.SAN',
                'VIDEO/2009_10.SAN', 'VIDEO/2009_10.TRS', 'VIDEO/ACCIDENT.SAN', 'VIDEO/ACCIDENT.TRS',
                'VIDEO/BARKDOG.SAN', 'VIDEO/BC.SAN', 'VIDEO/BENBURN.SAN', 'VIDEO/BENESCPE.SAN',
                'VIDEO/BENHANG.SAN', 'VIDEO/BENHANG.TRS', 'VIDEO/BIGBLOW.SAN', 'VIDEO/BOLUSKIL.SAN',
                'VIDEO/BOLUSKIL.TRS', 'VIDEO/BURST.SAN', 'VIDEO/BURSTDOG.SAN', 'VIDEO/CABSTRUG.SAN',
                'VIDEO/CES_NITE.SAN', 'VIDEO/CREDITS.SAN', 'VIDEO/CREDITS.TRS', 'VIDEO/DAZED.SAN',
                'VIDEO/DAZED.TRS', 'VIDEO/ESCPPLNE.SAN', 'VIDEO/ESCPPLNE.TRS', 'VIDEO/FANSTOP.SAN',
                'VIDEO/FI_14_15.SAN', 'VIDEO/FI_14_15.TRS', 'VIDEO/FIRE.SAN', 'VIDEO/FLINCH.SAN',
                'VIDEO/FULPLANE.SAN', 'VIDEO/GOTCHA.SAN', 'VIDEO/GOTCHA.TRS', 'VIDEO/GR_LOS.SAN',
                'VIDEO/GR_WIN.SAN', 'VIDEO/INTO_FAN.SAN', 'VIDEO/INTRO4.SAN', 'VIDEO/INTROD_8.SAN',
                'VIDEO/INTROD_8.TRS', 'VIDEO/JG.SAN', 'VIDEO/JUMPGORG.SAN', 'VIDEO/KICK_OFF.SAN',
                'VIDEO/KILLGULL.SAN', 'VIDEO/KR.SAN', 'VIDEO/KS_1.SAN', 'VIDEO/KS_1.TRS',
                'VIDEO/KS_11.SAN', 'VIDEO/KS_11.TRS', 'VIDEO/KS_111.SAN', 'VIDEO/KS_111.TRS',
                'VIDEO/KS_IV.SAN', 'VIDEO/KS_IV.TRS', 'VIDEO/KS_V.SAN', 'VIDEO/KS_V.TRS',
                'VIDEO/KS_X.SAN', 'VIDEO/MO_FUME.SAN', 'VIDEO/MOEJECT.SAN', 'VIDEO/MOEJECT.TRS',
                'VIDEO/MOREACH.SAN', 'VIDEO/MWC.SAN', 'VIDEO/MWC.TRS', 'VIDEO/NAMES_MO.SAN',
                'VIDEO/NAMES_MO.TRS', 'VIDEO/NB_BLOW.SAN', 'VIDEO/NITEFADE.SAN', 'VIDEO/NITERIDE.SAN',
                'VIDEO/NTREACT.SAN', 'VIDEO/OFFGOGG.SAN', 'VIDEO/OM.SAN', 'VIDEO/OM.TRS',
                'VIDEO/REALRIDE.SAN', 'VIDEO/REALRIDE.TRS', 'VIDEO/REV.SAN', 'VIDEO/RIDEAWAY.SAN',
                'VIDEO/RIDEOUT.SAN', 'VIDEO/RIP_KILL.SAN', 'VIDEO/RIP_KILL.TRS', 'VIDEO/RIPBROW.SAN',
                'VIDEO/RIPBROW.TRS', 'VIDEO/RIPSHIFT.SAN', 'VIDEO/SCRAPBOT.SAN', 'VIDEO/SCRAPBOT.TRS',
                'VIDEO/SEEN_RIP.SAN', 'VIDEO/SEEN_RIP.TRS', 'VIDEO/SHEFALLS.SAN', 'VIDEO/SHEFALLS.TRS',
                'VIDEO/SHORTOPN.SAN', 'VIDEO/SHOWSMRK.SAN', 'VIDEO/SHOWUP1.SAN', 'VIDEO/SHOWUP1.TRS',
                'VIDEO/SNAPFOTO.SAN', 'VIDEO/SNAPFOTO.TRS', 'VIDEO/SNSETRDE.SAN', 'VIDEO/SNSETRDE.TRS',
                'VIDEO/SQUINT.SAN', 'VIDEO/TC.SAN', 'VIDEO/TEETBURN.SAN', 'VIDEO/TINYPLNE.SAN',
                'VIDEO/TINYTRUK.SAN', 'VIDEO/TOKCRGO.SAN', 'VIDEO/TOKCRGO.TRS', 'VIDEO/TRKCRSH.SAN',
                'VIDEO/VISION.SAN', 'VIDEO/WEREINIT.SAN', 'VIDEO/WEREINIT.TRS', 'VIDEO/WHIP_PAN.SAN',
                'VIDEO/WHIP_PAN.TRS',
            ],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

        // ─── Revolution / freeware classics ──────────────────────────────
        'bass' => [
            'titulo'        => 'Beneath a Steel Sky',
            'descripcion'   => 'Cyberpunk distópico con guion del autor de Watchmen (Dave Gibbons). Robert Foster cae prisionero de la corporación que controla la ciudad y debe huir junto a su droide Joey. Versión freeware oficial liberada por Revolution.',
            'año'           => 1994,
            'desarrollador' => 'Revolution Software',
            'idioma'        => 'Inglés',
            'version'       => 'Freeware',
            'engine_id'     => 'sky',
            'scummvm_id'    => 'sky',
            'cover'         => '/img/games/bass.png',
            'files'         => ['sky.cpt', 'sky.dnr', 'sky.dsk'],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

        'queen' => [
            'titulo'        => 'Flight of the Amazon Queen',
            'descripcion'   => 'Aventura gráfica de los 90 al estilo LucasArts: Joe King, piloto de la Amazon Queen, se estrella en la jungla y debe rescatar a una estrella de cine secuestrada por un científico loco. Versión CD en español.',
            'año'           => 1995,
            'desarrollador' => 'Interactive Binary Illusions',
            'idioma'        => 'Español',
            'version'       => 'CD',
            'engine_id'     => 'queen',
            'scummvm_id'    => 'queen',
            'cover'         => '/img/games/queen.jpg',
            'files'         => ['queen.1c'],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

        // ─── Sierra / SCI engine ─────────────────────────────────────────
        'lsl1' => [
            'titulo'        => 'Leisure Suit Larry: In the Land of the Lounge Lizards',
            'descripcion'   => 'Remake VGA del clásico de 1987: Larry Laffer, treintañero virgen, llega a Lost Wages buscando aventuras amorosas en una sola noche. Comedia adulta de Al Lowe que definió un género.',
            'año'           => 1991,
            'desarrollador' => 'Sierra On-Line',
            'idioma'        => 'Español',
            'version'       => 'VGA Remake',
            'engine_id'     => 'sci',
            'scummvm_id'    => 'lsl1sci',
            'cover'         => '/img/games/lsl1.jpg',
            'files'         => [
                '300.SCR', '300.TEX', '720.scr', '927.SCR', 'RESOURCE.000',
                'RESOURCE.001', 'RESOURCE.002', 'RESOURCE.003', 'RESOURCE.MAP',
            ],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

        'lsl5' => [
            'titulo'        => 'Leisure Suit Larry 5: Passionate Patti Does a Little Undercover Work',
            'descripcion'   => 'Larry y Patti en historias paralelas: él trabaja para una televisión que busca el siguiente Top 10, ella es agente del FBI investigando a la mafia musical. Aventura con interfaz de iconos en VGA.',
            'año'           => 1991,
            'desarrollador' => 'Sierra On-Line',
            'idioma'        => 'Español',
            'version'       => 'Floppy',
            'engine_id'     => 'sci',
            'scummvm_id'    => 'lsl5',
            'cover'         => '/img/games/lsl5.jpg',
            'files'         => [
                '258.SCR', '280.SCR', '280.TEX', '961.V56', 'RESOURCE.000',
                'RESOURCE.001', 'RESOURCE.002', 'RESOURCE.003', 'RESOURCE.004', 'RESOURCE.005',
                'RESOURCE.006', 'RESOURCE.007', 'RESOURCE.MAP',
            ],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

        'castlebrain' => [
            'titulo'        => 'The Castle of Dr. Brain',
            'descripcion'   => 'Aventura-puzzle educativa: aspiras a ser ayudante del Dr. Brain y debes resolver acertijos de matemáticas, lógica, criptografía y trivia para entrar en su castillo. Sierra para mentes curiosas.',
            'año'           => 1991,
            'desarrollador' => 'Sierra On-Line',
            'idioma'        => 'Español',
            'version'       => 'DOS Floppy',
            'engine_id'     => 'sci',
            'scummvm_id'    => 'castlebrain',
            'cover'         => '/img/games/castlebrain.jpg',
            'files'         => [
                'BRAINSG.DIR', 'RESOURCE.000', 'RESOURCE.001', 'RESOURCE.MAP',
            ],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

        'laurabow2' => [
            'titulo'        => 'Laura Bow 2: The Dagger of Amon Ra',
            'descripcion'   => 'Misterio en el Museo de Historia Natural de Nueva York, 1926: Laura Bow investiga el robo de una daga egipcia y los asesinatos que la rodean. Suspense estilo Agatha Christie con interfaz de iconos.',
            'año'           => 1992,
            'desarrollador' => 'Sierra On-Line',
            'idioma'        => 'Español',
            'version'       => 'CD',
            'engine_id'     => 'sci',
            'scummvm_id'    => 'laurabow2',
            'cover'         => '/img/games/laurabow2.jpg',
            'files'         => [
                '0.FON', '0.msg', '1.FON', '10.FON', '10.msg',
                '100.msg', '110.msg', '111.AUD', '120.msg', '1207.FON',
                '13.msg', '1350.msg', '140.msg', '1440.msg', '1450.msg',
                '1490.msg', '15.msg', '1500.msg', '151.V56', '1510.msg',
                '1520.msg', '155.msg', '1550.msg', '1560.msg', '16.msg',
                '160.msg', '1600.msg', '18.msg', '180.msg', '1880.msg',
                '1882.msg', '1883.msg', '1884.msg', '1885.msg', '1886.msg',
                '1887.msg', '1888.msg', '1889.msg', '1890.msg', '1891.msg',
                '1892.msg', '1893.msg', '1894.msg', '19.msg', '190.msg',
                '1900.FON', '20.msg', '210.msg', '2107.FON', '2108.FON',
                '220.msg', '230.msg', '235.v56', '24.msg', '240.msg',
                '2407.FON', '250.msg', '2510.FON', '26.V56', '26.msg',
                '260.msg', '270.msg', '280.msg', '281.AUD', '282.AUD',
                '290.msg', '292.AUD', '295.msg', '300.msg', '310.msg',
                '312.AUD', '320.msg', '330.msg', '335.msg', '340.msg',
                '350.msg', '355.msg', '360.msg', '370.msg', '40.AUD',
                '400.msg', '41.AUD', '4115.FON', '42.AUD', '420.msg',
                '430.AUD', '430.msg', '435.msg', '44.AUD', '440.AUD',
                '440.msg', '441.AUD', '443.AUD', '444.AUD', '445.AUD',
                '448.msg', '45.AUD', '450.msg', '452.AUD', '453.AUD',
                '454.msg', '455.AUD', '455.msg', '46.AUD', '460.AUD',
                '460.msg', '462.AUD', '47.AUD', '48.AUD', '480.AUD',
                '480.msg', '481.AUD', '49.AUD', '490.AUD', '490.msg',
                '500.AUD', '500.msg', '501.AUD', '51.AUD', '510.msg',
                '52.AUD', '520.V56', '520.msg', '522.AUD', '523.AUD',
                '525.msg', '530.msg', '54.AUD', '543.AUD', '550.msg',
                '555.AUD', '556.AUD', '560.AUD', '560.msg', '561.AUD',
                '561.msg', '562.V56', '562.msg', '563.V56', '566.AUD',
                '6.V56', '60.FON', '600.AUD', '600.msg', '61.FON',
                '610.msg', '612.AUD', '620.msg', '630.msg', '631.AUD',
                '632.AUD', '633.AUD', '634.AUD', '635.AUD', '640.AUD',
                '640.V56', '640.msg', '641.AUD', '650.msg', '651.AUD',
                '652.AUD', '654.AUD', '660.msg', '69.FON', '700.AUD',
                '700.msg', '701.AUD', '710.AUD', '710.msg', '712.AUD',
                '713.AUD', '715.msg', '720.msg', '721.AUD', '722.AUD',
                '730.msg', '740.msg', '750.AUD', '750.msg', '751.AUD',
                '752.AUD', '760.V56', '770.AUD', '770.msg', '775.msg',
                '785.msg', '790.msg', '791.V56', '80.AUD', '8000.V56',
                '81.AUD', '82.AUD', '83.AUD', '84.AUD', '85.AUD',
                '851.V56', '857.V56', '91.msg', '954.msg', '96.AUD',
                '99.msg', '990.V56', '990.msg', '992.V56', '994.msg',
                '995.v56', '999.FON', 'LAURT.BMP', 'RESOURCE.000', 'RESOURCE.AUD',
                'RESOURCE.GEN', 'RESOURCE.MAP', 'RESOURCE.MT', 'RESOURCE.PRO', 'RESOURCE.SB',
                'RESOURCE.STD', 'RESOURCE.THN', 'SIERRA.BMP', 'TITLE.BMP',
            ],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

        'ecoquest' => [
            'titulo'        => 'EcoQuest: The Search for Cetus',
            'descripcion'   => 'Adam, hijo de un biólogo marino, debe encontrar al rey de las ballenas (Cetus) y limpiar el océano de contaminación. Aventura ecologista para niños con animaciones VGA y voces.',
            'año'           => 1991,
            'desarrollador' => 'Sierra On-Line',
            'idioma'        => 'Español',
            'version'       => 'CD',
            'engine_id'     => 'sci',
            'scummvm_id'    => 'ecoquest',
            'cover'         => '/img/games/ecoquest.jpg',
            'files'         => [
                '0.fon', '0.msg', '1.msg', '100.msg', '101.msg',
                '120.msg', '140.HEP', '140.SCR', '140.msg', '142.HEP',
                '142.SCR', '160.msg', '180.msg', '200.msg', '220.msg',
                '221.msg', '222.msg', '223.msg', '224.msg', '225.msg',
                '226.msg', '240.msg', '260.msg', '280.msg', '3.msg',
                '300.fon', '300.msg', '310.fon', '320.msg', '321.msg',
                '322.msg', '335.msg', '340.msg', '341.msg', '343.msg',
                '344.msg', '345.msg', '360.msg', '377.v56', '380.HEP',
                '380.SCR', '380.msg', '381.HEP', '381.SCR', '4.fon',
                '4.msg', '40.v56', '400.msg', '413.v56', '420.msg',
                '440.msg', '460.msg', '480.msg', '5.msg', '50.msg',
                '500.msg', '520.msg', '540.msg', '560.msg', '561.msg',
                '580.msg', '6.fon', '600.msg', '61.HEP', '61.SCR',
                '620.msg', '640.msg', '660.msg', '810.msg', '811.msg',
                '816.msg', '822.hep', '822.scr', '952.v56', '956.v56',
                '959.v56', '990.msg', '994.msg', '995.msg', '999.fon',
                'AUDIO/122.AUD', 'AUDIO/124.AUD', 'AUDIO/127.AUD', 'AUDIO/143.AUD', 'AUDIO/144.AUD',
                'AUDIO/145.AUD', 'AUDIO/146.AUD', 'AUDIO/164.AUD', 'AUDIO/165.AUD', 'AUDIO/167.AUD',
                'AUDIO/168.AUD', 'AUDIO/169.AUD', 'AUDIO/183.AUD', 'AUDIO/185.AUD', 'AUDIO/208.AUD',
                'AUDIO/209.AUD', 'AUDIO/210.AUD', 'AUDIO/211.AUD', 'AUDIO/212.AUD', 'AUDIO/213.AUD',
                'AUDIO/215.AUD', 'AUDIO/216.AUD', 'AUDIO/218.AUD', 'AUDIO/321.AUD', 'AUDIO/331.AUD',
                'AUDIO/333.AUD', 'AUDIO/334.AUD', 'AUDIO/362.AUD', 'AUDIO/370.AUD', 'AUDIO/382.AUD',
                'AUDIO/385.AUD', 'AUDIO/387.AUD', 'AUDIO/388.AUD', 'AUDIO/389.AUD', 'AUDIO/390.AUD',
                'AUDIO/391.AUD', 'AUDIO/392.AUD', 'AUDIO/393.AUD', 'AUDIO/394.AUD', 'AUDIO/395.AUD',
                'AUDIO/396.AUD', 'AUDIO/397.AUD', 'AUDIO/398.AUD', 'AUDIO/399.AUD', 'AUDIO/402.AUD',
                'AUDIO/403.AUD', 'AUDIO/404.AUD', 'AUDIO/405.AUD', 'AUDIO/406.AUD', 'AUDIO/407.AUD',
                'AUDIO/408.AUD', 'AUDIO/409.AUD', 'AUDIO/421.AUD', 'AUDIO/441.AUD', 'AUDIO/442.AUD',
                'AUDIO/461.AUD', 'AUDIO/462.AUD', 'AUDIO/463.AUD', 'AUDIO/464.AUD', 'AUDIO/465.AUD',
                'AUDIO/466.AUD', 'AUDIO/467.AUD', 'AUDIO/469.AUD', 'AUDIO/481.AUD', 'AUDIO/483.AUD',
                'AUDIO/484.AUD', 'AUDIO/485.AUD', 'AUDIO/500.AUD', 'AUDIO/501.AUD', 'AUDIO/502.AUD',
                'AUDIO/503.AUD', 'AUDIO/504.AUD', 'AUDIO/505.AUD', 'AUDIO/526.AUD', 'AUDIO/540.AUD',
                'AUDIO/541.AUD', 'AUDIO/542.AUD', 'AUDIO/561.AUD', 'AUDIO/562.AUD', 'AUDIO/581.AUD',
                'AUDIO/582.AUD', 'AUDIO/583.AUD', 'AUDIO/584.AUD', 'AUDIO/602.AUD', 'AUDIO/603.AUD',
                'AUDIO/641.AUD', 'AUDIO/644.AUD', 'AUDIO/645.AUD', 'AUDIO/646.AUD', 'AUDIO/647.AUD',
                'AUDIO/661.AUD', 'AUDIO/662.AUD', 'AUDIO/663.AUD', 'AUDIO/901.AUD', 'AUDIO/902.AUD',
                'AUDIO/903.AUD', 'AUDIO/904.AUD', 'AUDIO/905.AUD', 'AUDIO/906.AUD', 'AUDIO/907.AUD',
                'AUDIO/908.AUD', 'AUDIO/909.AUD', 'AUDIO/910.AUD', 'AUDIO/911.AUD', 'AUDIO/912.AUD',
                'AUDIO/913.AUD', 'AUDIO/914.AUD', 'AUDIO/915.AUD', 'AUDIO/916.AUD', 'AUDIO/917.AUD',
                'AUDIO/918.AUD', 'AUDIO/919.AUD', 'AUDIO/920.AUD', 'AUDIO/921.AUD', 'AUDIO/924.AUD',
                'AUDIO/926.AUD', 'CDW900E.LOG', 'ECOPIC.BMP', 'ISOAGR2', 'RESOURCE.000',
                'RESOURCE.AUD', 'RESOURCE.GEN', 'RESOURCE.MAP', 'RESOURCE.MT', 'RESOURCE.PRO',
                'RESOURCE.SB', 'RESOURCE.STD', 'RESOURCE.THN', 'SIERRA.BMP', 'TITLE.BMP',
                'TSN/CCPATCH/130.SO', 'TSN/HOSTADDR', 'TSN/INSTTSN.HLP', 'TSN/LLPATCH/1040.SO', 'TSN/LLSYSTEM.DAT',
                'TSN/MT32.NL', 'TSN/PART.1', 'TSN/PART.2', 'TSN/PART.3', 'TSN/PART.4',
                'TSN/RESOURCE.001', 'TSN/RESOURCE.MAP', 'TSN/SLPATCH/120.SO', 'TSN/TSN.PIF', 'TSN/TSN.PRG',
                'TSN/_ARRYLND.DOC', 'TSN/_ENERAL.DOC', 'TSN/_IERRLND.DOC', 'TSN/_SERBIUS.DOC', 'leeme.htm',
            ],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

        'ecoquest2' => [
            'titulo'        => 'EcoQuest 2: Lost Secret of the Rainforest',
            'descripcion'   => 'Adam viaja a la selva amazónica con su padre para investigar la deforestación. Conoce a Paquita, una niña indígena, y juntos enfrentan a una empresa minera que destruye el bosque.',
            'año'           => 1993,
            'desarrollador' => 'Sierra On-Line',
            'idioma'        => 'Español',
            'version'       => 'Floppy',
            'engine_id'     => 'sci',
            'scummvm_id'    => 'ecoquest2',
            'cover'         => '/img/games/ecoquest2.jpg',
            'files'         => [
                '390.SCR', '65535.MAP', 'MESSAGE.MAP', 'RESOURCE.000', 'RESOURCE.AUD',
                'RESOURCE.MAP', 'RESOURCE.MSG',
            ],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

        'freddypharkas' => [
            'titulo'        => 'Freddy Pharkas: Frontier Pharmacist',
            'descripcion'   => 'Comedia western de Al Lowe y Josh Mandel: Freddy es un farmacéutico retirado del oeste que vuelve a tomar las pistolas cuando el pueblo de Coarsegold queda envenenado. Voces y comedia absurda.',
            'año'           => 1993,
            'desarrollador' => 'Sierra On-Line',
            'idioma'        => 'Español',
            'version'       => 'CD Talkie',
            'engine_id'     => 'sci',
            'scummvm_id'    => 'freddypharkas',
            'cover'         => '/img/games/freddypharkas.jpg',
            'files'         => [
                '0.fon', '0.msg', '10.fon', '110.msg', '1207.fon',
                '13.msg', '143.p56', '144.p56', '145.p56', '146.p56',
                '147.p56', '15.hep', '15.msg', '15.scr', '150.fon',
                '150.msg', '153.v56', '16.msg', '170.msg', '171.v56',
                '175.v56', '18.msg', '1807.fon', '19.msg', '190.v56',
                '200.msg', '210.msg', '2107.fon', '2108.fon', '220.msg',
                '230.msg', '235.msg', '24.msg', '240.msg', '2407.fon',
                '250.msg', '2510.fon', '253.v56', '255.v56', '26.msg',
                '260.msg', '265.msg', '270.msg', '2998.SYN', '2999.SYN',
                '30.fon', '300.msg', '310.msg', '32.msg', '320.msg',
                '400.msg', '410.msg', '4115.fon', '420.msg', '500.msg',
                '540.msg', '550.msg', '550.p56', '560.msg', '570.msg',
                '6.v56', '60.fon', '600.msg', '61.fon', '610.msg',
                '620.msg', '625.hep', '625.scr', '630.msg', '631.v56',
                '640.msg', '650.msg', '660.msg', '670.msg', '671.msg',
                '675.msg', '680.p56', '680.v56', '69.fon', '690.msg',
                '700.msg', '710.msg', '720.msg', '730.msg', '740.msg',
                '790.msg', '790.v56', '791.msg', '791.v56', '792.v56',
                '793.v56', '794.v56', '795.v56', '796.v56', '797.v56',
                '798.v56', '799.v56', '90.hep', '90.msg', '90.scr',
                '90.v56', '928.hep', '928.scr', '99.msg', '990.msg',
                '990.v56', '991.v56', '992.v56', '994.msg', '995.v56',
                '999.fon', 'AUDIO/0.MAP', 'AUDIO/15.MAP', 'AUDIO/16.MAP', 'AUDIO/18.MAP',
                'AUDIO/19.MAP', 'AUDIO/200.MAP', 'AUDIO/210.MAP', 'AUDIO/220.MAP', 'AUDIO/230.MAP',
                'AUDIO/235.MAP', 'AUDIO/240.MAP', 'AUDIO/250.MAP', 'AUDIO/26.MAP', 'AUDIO/260.MAP',
                'AUDIO/265.MAP', 'AUDIO/270.MAP', 'AUDIO/300.MAP', 'AUDIO/310.MAP', 'AUDIO/32.MAP',
                'AUDIO/320.MAP', 'AUDIO/400.MAP', 'AUDIO/410.MAP', 'AUDIO/420.MAP', 'AUDIO/500.MAP',
                'AUDIO/540.MAP', 'AUDIO/560.MAP', 'AUDIO/570.MAP', 'AUDIO/576.MAP', 'AUDIO/600.MAP',
                'AUDIO/610.MAP', 'AUDIO/620.MAP', 'AUDIO/630.MAP', 'AUDIO/640.MAP', 'AUDIO/650.MAP',
                'AUDIO/660.MAP', 'AUDIO/670.MAP', 'AUDIO/671.MAP', 'AUDIO/675.MAP', 'AUDIO/690.MAP',
                'AUDIO/700.MAP', 'AUDIO/710.MAP', 'AUDIO/720.MAP', 'AUDIO/730.MAP', 'AUDIO/740.MAP',
                'AUDIO/791.MAP', 'AUDIO/90.MAP', 'AUDIO/99.MAP', 'AUDIO/RESOURCE.AUD', 'RESOURCE.000',
                'RESOURCE.MAP', 'RESOURCE.SFX',
            ],
            'ini'           => ['language' => 'es', 'subtitles' => true],
        ],

    ],
];
